name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.12.1 [CE|EE|ECE 2.4.0-2.4.7] 19 May 2025
          tag_name: 1.12.1
          body: |2-
            ### softcommerce/module-plenty-order-profile-schedule [1.3.1]
            - **Enhancement**: Efficient Order Export Using Status Filters [#63]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
