name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.13.0 [CE|EE|ECE 2.4.0-2.4.7] 28 May 2025
          tag_name: 1.13.0
          body: |2-
            ### softcommerce/module-core [1.6.1]
            - **Enhancement**: Enhanced Configurable-Product Detection in Export/Import Interface [#64]

            ### softcommerce/module-plenty-item [1.6.0]
            - **Feature**: Allow Export of “Not Visible Individually” Products to PlentyMarkets [#66]
            - **Enhancement**: Add Pagination to Product Chooser Modal in Product Export Listing [#65]

            ### softcommerce/module-plenty-item-profile [1.13.0]
            - **Feature**: Allow Export of “Not Visible Individually” Products to PlentyMarkets [#66]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
