name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.13.1 [CE|EE|ECE 2.4.0-2.4.7] 11 Jun 2025
          tag_name: 1.13.1
          body: |2-
            ### softcommerce/module-plenty-item [1.6.1]
            - **Enhancement** Add isShippingType() Method to Plenty Item Modules [#69]

            ### softcommerce/module-plenty-order-profile [1.11.1]
            - **Fix** Support Multiple Tracking Numbers in Order Shipping Import [#68]
            - **Enhancement** Ensure Sales Order Grid Reindexing for Orders Skipped by Export [#67]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
