name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.10.2 [CE|EE|ECE 2.4.0-2.4.7] 29 Apr 2025
          tag_name: 1.10.2
          body: |2-
            ### softcommerce/module-plenty-client [1.4.3]
            - **Enhancement**: Removed unused database schema declaration.

            ### softcommerce/module-plenty-customer [1.3.4]
            - **Enhancement**: Removed unused database schema declaration.

            ### softcommerce/module-plenty-item-profile [1.11.1]
            - **Enhancement**: Removed unused database schema declaration.

            ### softcommerce/module-plenty-profile [1.5.2]
            - **Enhancement**: Removed unused database schema declaration.

            ### softcommerce/module-plenty-property [1.3.8]
            - **Enhancement**: Removed unused database schema declaration.

            ### softcommerce/module-plenty-stock [1.4.2]
            - **Enhancement**: Removed unused database schema declaration.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
