name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.10.1 [CE|EE|ECE 2.4.0-2.4.7] 09 Apr 2025
          tag_name: 1.10.1
          body: |2-
            ### softcommerce/module-plenty-order-profile [1.10.1]
            - **Enhancement** Added the ability to conditionally add product options to order line items based on defined rules.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
