name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.8.2 [CE|EE|ECE 2.4.0-2.4.7] 23 Jan 2025
          tag_name: 1.8.2
          body: |2-
            ### softcommerce/module-plenty-order-profile [1.8.2]
            - **Enhancement**: Applied a fix to resolved an issue affecting orders from third-party sales channels. These orders were getting stuck in the scheduling queue repeatedly because their status wasn’t updating properly after processing. This caused the system to attempt processing them over and over without success. The fix ensures that the status updates correctly, preventing orders from being stuck and allowing them to move through the system smoothly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
