name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.11.0 [CE|EE|ECE 2.4.0-2.4.7] 07 May 2025
          tag_name: 1.11.0
          body: |2-
            ### softcommerce/module-plenty-item-profile [1.12.0]
            - **Feature**: New CLI Command to Clear Product Mappings [#61]
            - **Fix**: Override Configurable Attribute Values on Product Export [#60]

            ### softcommerce/module-plenty-order-profile [1.11.0]
            - **Feature**: Option to Exclude Warehouse Assignment on Order Line Items [#62]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
