name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.10.4 [CE|EE|ECE 2.4.0-2.4.7] 06 May 2025
          tag_name: 1.10.4
          body: |2-
            ### softcommerce/module-plenty-order-profile [1.10.2]
            - **Fix** Ensure Customer Address Relation Is Always Assigned [#58]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
