name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.12.0 [CE|EE|ECE 2.4.0-2.4.7] 08 May 2025
          tag_name: 1.12.0
          body: |2-
            ### softcommerce/module-core [1.6.0]
            - **Compatibility**: Added compatibility for Magento 2.4.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
