name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.9.2 [CE|EE|ECE 2.4.0-2.4.7] 26 Feb 2025
          tag_name: 1.9.2
          body: |2-
            ### softcommerce/module-plenty-order-profile [1.9.2]
            - **Enhancement**: A fix has been implemented to correct VAT rate exports for order items. Previously, bundle items without a VAT reference in the Magento sales order table were mistakenly exported with a 0% VAT rate, and this update ensures the correct rate is now exported. [#49]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
