name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.9.0 [CE|EE|ECE 2.4.0-2.4.7] 05 Feb 2025
          tag_name: 1.9.0
          body: |2-
            ### softcommerce/module-plenty-order [1.5.0]
            - **Feature**: Added functionality to refresh sales order grid using CLI [#45]

            ### softcommerce/module-plenty-order-profile [1.9.0]
            - **Feature**: Added new feature to map PlentyONE and Magento orders using CLI [#46]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
