name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.10.5 [CE|EE|ECE 2.4.0-2.4.7] 07 May 2025
          tag_name: 1.10.5
          body: |2-
            ### softcommerce/module-plenty-item-profile [1.11.3]
            - **Compatibility**: Proper Cache Invalidation for Varnish After Product Import [#59]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
