name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.10.3 [CE|EE|ECE 2.4.0-2.4.7] 30 Apr 2025
          tag_name: 1.10.3
          body: |2-
            ### softcommerce/module-plenty-item-profile [1.11.2]
            - **Enhancement**: Validation error found :: attribute values do not match the other variations [#57]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
